apiVersion: v1
kind: ServiceAccount
metadata:
  name: k1-ready    
  namespace: default
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k1-informer
rules:
  - apiGroups: [""]
    resources: ["nodes", "services", "pods", "endpoints","secrets","secrets","configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["k1.kubefirst.io"]
    resources: ["watchers","watchers/status"]
    verbs: ["*"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k1-informer-crb
subjects:
- kind: ServiceAccount
  name: k1-ready
  namespace: default
roleRef:
  kind: ClusterRole
  name: k1-informer
  apiGroup: rbac.authorization.k8s.io

---
