apiVersion: k1.kubefirst.io/v1beta1
kind: Watcher
metadata:
  labels:
    app.kubernetes.io/name: watcher
    app.kubernetes.io/instance: watcher-sample
    app.kubernetes.io/part-of: watcher
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: watcher
  name: watcher-sample
spec:
  # TODO(user): Add fields here
